### ISSUE TITLE
Bitmap not working with unmoving text display

### ISSUE THREAD

**Issue by richardjm** [o0shojo0o/PixelIt#175]
Expected behaviour - text appears beside icon.
What happens - text appears on the left without icon.

REST call - change `"Hello World"` to `"Hello"` or set `"scrollText"` to `false` to create issue
```json
{
    "bitmap": {
        "data": [0, 52857, 52857, 52857, 52857, 52857, 0, 0, 0, 52857, 53247, 53247, 53247, 52857, 0, 0, 0, 52857, 53247, 53247, 53247, 52857, 0, 0, 0, 0, 52857, 53247, 52857, 0, 0, 0, 0, 0, 0, 52857, 0, 0, 0, 0, 0, 0, 52857, 0, 52857, 0, 0, 0, 0, 52857, 0, 0, 0, 52857, 0, 0, 0, 52857, 52857, 52857, 52857, 52857, 0, 0]
    },
    "text": {
        "textString": "Hello World",
        "bigFont": false,
        "scrollText": "auto",
        "centerText": false,
        "color": {
            "r": 255,
            "g": 255,
            "b": 255
        }
    }
}
```

Workaround is to use a call like
```yaml
{
    "bitmapAnimation": {
        "data": [ [0, 52857, 52857, 52857, 52857, 52857, 0, 0, 0, 52857, 53247, 53247, 53247, 52857, 0, 0, 0, 52857, 53247, 53247, 53247, 52857, 0, 0, 0, 0, 52857, 53247, 52857, 0, 0, 0, 0, 0, 0, 52857, 0, 0, 0, 0, 0, 0, 52857, 0, 52857, 0, 0, 0, 0, 52857, 0, 0, 0, 52857, 0, 0, 0, 52857, 52857, 52857, 52857, 52857, 0, 0]]
    },
    "text": {
        "textString": "Hello World",
        "bigFont": false,
        "scrollText": false,
        "centerText": false,
        "position": {
            "x": 8,
            "y": 1
        },
        "color": {
            "r": 255,
            "g": 255,
            "b": 255
        }
    }
}
```
